### ISSUE TITLE
it looks like the vote button gets an error on heroku

### ISSUE THREAD

**Issue by HayfordMD** [blairanderson/rails-hackernews-reddit-producthunt-clone#4]
Not sure if anyone still works on this but on the heroku test deploy it seem the vote button fails.

**Comment by blairanderson** [comment]
Have you tried this locally?

**Comment by HayfordMD** [comment]
I didn't try it locally. I was curious about the web app so I tired the
demo. No big deal just thought it might be worth noting to someone.

**Comment by blairanderson** [comment]
hey fwiw this is fixed. Just needed to run the migration :grin:
